services:
  db:
    image: mariadb:10.6
    environment:
      MARIADB_DATABASE: algorithm_hub
      MARIADB_USER: algouser
      MARIADB_PASSWORD: algopass
      MARIADB_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    depends_on:
      - db
    ports:
      - "8087:80"
    networks:
      - internal

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: algouser
      DB_PASSWORD: algopass
      DB_NAME: algorithm_hub
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
    expose:
      - "3000"

  frontend:
    build: ./frontend
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - backend
    networks:
      - internal
    ports:
      - "80:80"

networks:
  internal:
    driver: bridge

volumes:
  db_data:
